### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by tubinan-bowan** [silianpan/uniapp-admin#6]
您家这个模版为什么switch不能设置颜色？烦劳有空给个回复

**Comment by lavieAll** [comment]
http://ua-doc.silianpan.cn/
参考文档《主题定制》

这里只定制了导航条背景颜色，在pages.json中的每个跳转页面onReady生命周期函数中设置如下：

注意：为了实时生效，需要在每个页面的onShow生命周期中设置
