### ISSUE TITLE
项目绑定云空间后H5端无法运行

### ISSUE THREAD

**Issue by MonsterGene** [silianpan/uniapp-admin#7]
您好，首先感谢您开发这个好项目。

我在使用这个创建项目后，绑定云空间，在微信小程序端可以正常运行，但在H5端却报错“uni not defined”，请问这个问题是怎么回事呢？

**Comment by lavieAll** [comment]
需要查看h5端兼容云空间问题

**Comment by ws228** [comment]
大佬，怎么配置后端，让项目跑起呢？

**Comment by dewen2018** [comment]
大佬，有开源后端代码吗

**Comment by silianpan** [comment]
每个团队都有不同的后端架构，没有开源后端代码，可以加我沟通：2480621579@qq.com

**Comment by silianpan** [comment]
> 

每个团队都有不同的后端架构，没有开源后端代码，可以加我QQ沟通：2480621579

**Comment by lavieAll** [comment]
> 大佬，有开源后端代码吗

每个团队都有不同的后端架构，没有开源后端代码，可以加我QQ沟通：2480621579

**Comment by lavieAll** [comment]
> 



> 大佬，怎么配置后端，让项目跑起呢？

可以加我QQ沟通：2480621579
